### ISSUE TITLE
Example for custom dataset

### ISSUE THREAD

**Issue by ooguz166** [Yura52/rtdl#27]
Hi ! are there any examples for extracting embedings for custom tabular data ?

regards

**Comment by Yura52** [comment]
> Hi ! are there any examples for extracting embedings for custom tabular data ?

Hi! What do you mean by "extracting embeddings for custom tabular data"? If you want to experiment with your custom dataset, you can take inspiration from our datasets and prepare your data in the same format.

**Comment by ooguz166** [comment]
thanks for the reply. And yes I do get the  inspiration after spending some time. Great repo. I'll deff.  dig in.

regards, closing the issue

**Comment by Yura52** [comment]
@ooguz166 hi!

We are reorganizing the codebase and I am transfering the issues to proper repositories. Could you tell about which project your question was? (1) rtdl library or (2) "Revisiting Deep Learning Models for Tabular Data" or (3) "On Embeddings for Numerical Features in Tabular Deep Learning" ?
