### ISSUE TITLE
Bugs in piecewise-linear encoding

### ISSUE THREAD

**Issue by Yura52** [Yura52/rtdl#38]
1. [Here](https://github.com/Yura52/rtdl/blob/448d590995246039b0eb75f26d80e8094d4d5016/rtdl/data.py#L445), `indices = as_tensor(values)` must be changed to this:

```
indices = as_tensor(indices)
```

2. [Here](https://github.com/Yura52/rtdl/blob/448d590995246039b0eb75f26d80e8094d4d5016/rtdl/data.py#L468), `np.array(d_encoding)` must be changed to this:

```
torch.tensor(d_encoding).to(indices)
```

3. [Here](https://github.com/Yura52/rtdl/blob/448d590995246039b0eb75f26d80e8094d4d5016/rtdl/data.py#L249), the argument `dtype=X.dtype` is missing for `np.array`

4. [Here](https://github.com/Yura52/rtdl/blob/448d590995246039b0eb75f26d80e8094d4d5016/rtdl/data.py#L109), `.to(X)` is missing

5. [Here](https://github.com/Yura52/rtdl/blob/448d590995246039b0eb75f26d80e8094d4d5016/rtdl/data.py#L610), it must be:

```
is_last_bin = bin_indices + 1 == as_tensor(list(map(len, bin_edges)))
```

**Comment by Dont-Care-Didnt-Ask** [comment]
6. [Here](https://github.com/Yura52/rtdl/blob/448d590995246039b0eb75f26d80e8094d4d5016/rtdl/data.py#L389) it should be
```
        if (
            (c_values < effective_c_bin_edges[c_indices]).any()
            or (c_values > effective_c_bin_edges[c_indices + 1]).any()
        ):
```

**Comment by daniil-shlenskii** [comment]
[Here](https://github.com/Yura52/rtdl/blob/448d590995246039b0eb75f26d80e8094d4d5016/rtdl/data.py#L109), it must be
```
quantiles = torch.linspace(0.0, 1.0, adjusted_n_bins + 1).to(column.device)
```
