### ISSUE TITLE
Cannot link in the document of zero

### ISSUE THREAD

**Issue by WuZheng326** [Yura52/rtdl#39]
Hi! I am trying to understand the usage of python package zero, which is used in the example of rtdl. But I found that the linkage in the comment line of the code is not available anymore.

Here is the invalid link: 
https://yura52.github.io/zero/0.0.4/reference/api/zero.improve_reproducibility.html

I am wondering is there any other document? Thank you!

Regards.

**Comment by Yura52** [comment]
Hi @WuZheng326 , thank you for reporting! The correct link is https://yura52.github.io/delu/0.0.4

JFYI: the library "Zero" was renamed to "DeLU", this is why the link to older versions changed.

**Comment by WuZheng326** [comment]
> 

Great! Thank you for reply! 

regards, closing the issue

**Comment by Yura52** [comment]
I'll keep this open as a reminder for me to fix the issue :)

**Comment by WuZheng326** [comment]
Great! Respect!
