### ISSUE TITLE
Regression results about the RTDL models.

### ISSUE THREAD

**Issue by linkedlist771** [Yura52/rtdl#42]
>Hi, you did a great implementation of the tab-transformer. However, when I use your example notebook to do the simple regression for the Sin(x), neither the baseline model or the FTTransformer give the good results.  I have no idea about this and want to know why. 

>Here is the [link](https://colab.research.google.com/drive/1G8tHZypX-Fvhq7COwFsjgbboJYXL1jdq?usp=sharing)

**Comment by Yura52** [comment]
In the cell where the training happens, you have warnings that correctly point to the issue. To fix this, you have to make `y_all` a **one-dimensional** array. Namely, instead of this line:

```
y_all = np.sin(X_all).astype('float32').reshape(-1, 1)
```

you should do this:

```
y_all = np.sin(X_all).astype('float32').squeeze(1)
```
