### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by jdefriel** [Yura52/rtdl#47]
Hello,

I am trying to use PiecewiseLinearEncoder(). I think I found a few typos. Please check my work. 

I first ran into an issue in piecewise_linear_encoding where I got the error in line 618 saying "RuntimeError: The size of tensor a (3688) must match the size of tensor b (32) at non-singleton dimension 1"

I dug into the code and found that when PiecewiseLinearEncoder was calling piecewise_linear_encoding the positional arguments of indices and ratios were switched in the former from what was expected in the latter.

Additionally, when inspecting piecewise_linear_encoding it looks like bin_edges = as_tensor(bin_ratios) not "as_tensor(bin_edges)" which would make more sense.

Can you please check this out? Much appreciated.

**Comment by Yura52** [comment]
Hello, thank you very much for your work, indeed those are bugs in both cases.

P.S. This part of the codebase is not yet released and is very much work in progress. And currently, I do not have reliable estimates of when and if it fill be finished.
