### ISSUE TITLE
rtdl example on dataset with categorical variables

### ISSUE THREAD

**Issue by bioshot-dotcom** [Yura52/rtdl#48]
Hi! Is it possible to have an example which involves also categorical variables?

**Comment by mtreca** [comment]
You can find a commented section on categorical variables in their example notebook [here](https://github.com/Yura52/rtdl/blob/main/examples/rtdl.ipynb) (look for the commented block starting with `=== ABOUT CATEGORICAL FEATURES ===`).

**Comment by Yura52** [comment]
@mtreca thank you for the reply!

@bioshot-dotcom feel free to ask further questions if needed
