### ISSUE TITLE
# bug, located in rtdl.data.piecewise_linear_encoding line #618

### ISSUE THREAD

**Issue by grayicon** [Yura52/rtdl#54]
"is_last_bin = bin_indices + 1 == torch.as_tensor(list(map(len, bin_edges)))is_last_bin = bin_indices + 1 == torch.as_tensor(list(map(len, bin_edges)))" should be "is_last_bin = bin_indices + 1 == torch.as_tensor(list(map(len, bin_edges)))is_last_bin = bin_indices + 1 == torch.as_tensor(list(map(len, bin_edges))).unsqueeze(-1))", to use tensor broadcast func

**Comment by Yura52** [comment]
Thank you for the report. Currently, the main branch contains significant amount of unfinished work nor released to PyPI, so bugs are expected, and use it at your own risk.

P.S. The formatted version of the above bug report:

instead of this:
```
is_last_bin = bin_indices + 1 == torch.as_tensor(list(map(len, bin_edges)))
```
it should be this:
```
is_last_bin = bin_indices + 1 == torch.as_tensor(list(map(len, bin_edges))).unsqueeze(-1))
```

**Comment by Yura52** [comment]
@grayicon is it actually a bug?

- `bin_indices + 1` has the shape `(n_objects, n_features)`
- `as_tensor(list(map(len, bin_edges)))` has the shape `(n_features,)`
- According to broadcasting rules, the result `is_last_bin` has the shape `(n_objects, n_features)`

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed.

**Comment by grayicon** [comment]
> @grayicon is it actually a bug?
> 
> * `bin_indices + 1` has the shape `(n_objects, n_features)`
> * `as_tensor(list(map(len, bin_edges)))` has the shape `(n_features,)`
> * According to broadcasting rules, the result `is_last_bin` has the shape `(n_objects, n_features)`

The above desc is right in theory,  but in fact i found the real bug lie in the line #590 of rtdl.data.py "bin_edges = torch.as_tensor(bin_ratios)",  which  cause the  state "as_tensor(list(map(len, bin_edges)))"  has the shape (n_objects,)

**Comment by Yura52** [comment]
So it seems to be the issue reported here, right?

https://github.com/Yura52/rtdl/issues/47

**Comment by Yura52** [comment]
So it should be now resolved by https://github.com/Yura52/rtdl/commit/7929497c6f37f4cd738ffcd5584642cb1d016ae3

Please, let me know if the issue still there

**Comment by grayicon** [comment]
> So it should be now resolved by [7929497](https://github.com/Yura52/rtdl/commit/7929497c6f37f4cd738ffcd5584642cb1d016ae3)
> 
> Please, let me know if the issue still there

The bin_egdes is a list of torch tensor, So it doesn't support the opera of 'torch.as_tensor'. Consequently, I just comment this line "bin_edges = torch.as_tensor(bin_ratios)", and it will works when call of "map(len, bin_edges) below".

**Comment by Yura52** [comment]
@grayicon oh, I think now I understand. I removed this line in [this commit](https://github.com/Yura52/rtdl/commit/60ae9814585d9792e112608a27e2bbbbdcbd3388). Does it look good now?

**Comment by grayicon** [comment]
> @grayicon oh, I think now I understand. I removed this line in [this commit](https://github.com/Yura52/rtdl/commit/60ae9814585d9792e112608a27e2bbbbdcbd3388). Does it look good now?

Yes，It can work now, Thanks for your effort.
