### ISSUE TITLE
How to get feature importance scores or attention heatmap

### ISSUE THREAD

**Issue by Yuntian9708** [Yura52/rtdl#56]
Hi, 
I am trying to get some visualizations of interpretable results from FT-Transformer, such as feature importance or attention heatmaps. I find some discussions about feature importance in paper section 5.3, but I don't know how to achieve it.  Is there a way to achieve these based on the source codes you published? Or can you make an example of implementation? 
Thank you very much!

**Comment by Yura52** [comment]
Please, see [this issue](https://github.com/yandex-research/tabular-dl-revisiting-models/issues/2)

P.S. The implementation of the paper is now located here: https://github.com/yandex-research/tabular-dl-revisiting-models

**Comment by Yura52** [comment]
If you need further help, feel free to create a new issue in that repository or continue the discussion in the issue I mentioned
